Branch hm 3
Vypsen/fefu_backend_3_6 pull request #10
Opened 2022-04-01 15:21 UTC by Vypsen

2022-04-03 16:13 UTC, tonighty requested changes

2022-04-03 16:13 UTC, tonighty commented on backend_fefu_3_6/app/Http/Controllers/ListNewsWebController.php
> +class ListNewsWebController extends Controller
не нужно под список делать отдельный контроллер. у тя должен быть просто (Page|News)WebController с методами index и show.

2022-04-03 16:13 UTC, tonighty commented on backend_fefu_3_6/app/Http/Controllers/ListNewsWebController.php
> +        $list_news_paginate = News::paginate(5);
переменные в пхп принято обывать в `camelCase` ($newsList)

2022-04-03 16:13 UTC, tonighty commented on backend_fefu_3_6/app/Http/Controllers/ListNewsWebController.php
> +        $list_news_paginate = News::paginate(5);
News::query()->**published()**->paginate(...

2022-04-03 16:13 UTC, tonighty commented on backend_fefu_3_6/app/OpenApi/Schemas/PoginatorLinksSchema.php
> +class PoginatorLinksSchema extends SchemaFactory implements Reusable
pAginator

2022-04-03 16:13 UTC, tonighty commented on backend_fefu_3_6/app/OpenApi/Schemas/PoginatorMetaSchema.php
> +class PoginatorMetaSchema extends SchemaFactory implements Reusable
pAginator

2022-04-03 16:13 UTC, tonighty commented on backend_fefu_3_6/app/Http/Controllers/NewsApiController.php
> +    #[OpenApi\Response(factory: NotFoundResponse::class, statusCode: 404)]
а как тут может быть ошибка 404?

2022-04-03 16:13 UTC, tonighty commented on backend_fefu_3_6/app/Http/Controllers/PageApiController.php
> +    #[OpenApi\Response(factory: NotFoundResponse::class, statusCode: 404)]
а как тут может быть ошибка 404? №2

2022-04-03 16:13 UTC, tonighty commented on backend_fefu_3_6/app/Http/Controllers/ListPageWebController.php
> +        $list_page_paginate = Page::paginate(5);
переменные в пхп принято обывать в camelCase №2

2022-04-04 03:41 UTC, tonighty requested changes

2022-04-04 03:41 UTC, tonighty commented on backend_fefu_3_6/app/Http/Controllers/NewsWebController.php
> +        if ($listNews === null) {
$listNews не может быть null

2022-04-04 03:41 UTC, tonighty commented on backend_fefu_3_6/app/Http/Controllers/PageWebController.php
> +        if ($listPage === null) {
$listPage не может быть null))

2022-04-04 03:48 UTC, Vypsen commented on backend_fefu_3_6/app/Http/Controllers/NewsWebController.php
> +        if ($listNews === null) {
А если бд пустая, он просто пустую страницу выдаст?

2022-04-04 03:49 UTC, tonighty commented on backend_fefu_3_6/app/Http/Controllers/NewsWebController.php
> +        if ($listNews === null) {
в идеале – да. если на фронте ниче не сломается

2022-04-04 03:52 UTC, merged