Branch hm 4
Vypsen/fefu_backend_3_6 pull request #11
Opened 2022-04-08 03:57 UTC by Vypsen

2022-04-12 00:52 UTC, chrn-feip requested changes

2022-04-12 00:52 UTC, chrn-feip commented on backend_fefu_3_6/api-docs.json
> +                "summary": "Display the specified resource.",
Это описание того, что делает данный endpoint. Он точно ничего не показывает, поэтому описание некорректно.

2022-04-12 00:52 UTC, chrn-feip commented on backend_fefu_3_6/api-docs.json
> +                        "$ref": "#\/components\/responses\/"
Что-то потерялось тут

2022-04-12 00:52 UTC, chrn-feip commented on backend_fefu_3_6/api-docs.json
> +            "": {
Такое работает и при повторной генерации протокола не ломается?

2022-04-12 00:52 UTC, chrn-feip commented on backend_fefu_3_6/app/Http/Controllers/Api/AppealApiController.php
> +        $appeal->phone = PhoneSanitizer::sanitize($data['phone']);
Тут и для почты нужно ещё дописать $data[...] ?? null. Потому что телефон и почта не являются обязательными и их могут просто не передать в API запросе, т.е. и в массив $data не попадут. А если их там не будет, то попытка обратиться по ключу в массиве приведёт к ошибке.

2022-04-12 00:52 UTC, chrn-feip commented on backend_fefu_3_6/app/Http/Requests/AppealFormRequest.php
> +    protected function failedValidation(Validator $validator)
Некорректно использовать этот метод в классе, который работает и в веб, и в API контроллере. Вы сейчас не сможете получить правильное поведение в веб-форме, потому что там прежде выполнялся редирект с собранными ошибками, а не исключение с json.
![image](https://user-images.githubusercontent.com/40585429/162851870-d22b9d5b-7ecc-4eaf-9972-5167c0ab0a66.png)

Пока такой вариант можно использовать только в классе-наследнике. Т.о. для веба будет один класс запроса формы, а для апи другой (с этим методом)

2022-04-12 00:52 UTC, chrn-feip commented on backend_fefu_3_6/app/Http/Requests/AppealFormRequest.php
> +    protected function passedValidation()
Зачем этот метод? Зачем исключением (что само по себе признак "что-то пошло не так") эмулировать успешный json ответ? Тем более до момента, когда данные запроса будут как-то обработаны. Успешный ответ нужно в самом контроллере возвращать и не в виде исключения.

2022-04-12 00:52 UTC, chrn-feip commented on backend_fefu_3_6/docker-compose.yml
> -        restart: always
Это зачем понадобилось и почему в коммите с ДЗ про обращения?

2022-04-12 15:04 UTC, Vypsen commented
пофиксил

2022-04-13 09:41 UTC, chrn-feip requested changes

2022-04-13 09:41 UTC, chrn-feip commented on backend_fefu_3_6/app/Http/Controllers/Api/AppealApiController.php
> +        $appeal->name = $data['name'] ?? null;
Речь была про телефон и почту. Имя является обязательным для запроса, поэтому его не может не быть.

2022-04-13 09:41 UTC, chrn-feip commented on backend_fefu_3_6/docker-compose.yml
> -        restart: always
?

2022-04-13 11:48 UTC, merged