Branch hm 8
Vypsen/fefu_backend_3_6 pull request #15
Opened 2022-05-21 16:02 UTC by Vypsen

2022-05-22 06:13 UTC, chrn-feip requested changes

2022-05-22 06:13 UTC, chrn-feip commented on backend_fefu_3_6/app/Enums/AbstractEnum.php
> +class AbstractEnum
abstract class

2022-05-22 06:13 UTC, chrn-feip commented on backend_fefu_3_6/app/Enums/ProductAttributeType.php
> +class ProductAttributeType extends AbstractEnum
final class

2022-05-22 06:13 UTC, chrn-feip commented on backend_fefu_3_6/app/Http/Resources/ProductResources.php
> +class ProductResources extends JsonResource
1. Для списка и для запроса отдельного товара нужны разные ресурсы. Для списка нужен минимум информации и товаров в списке много может быть, если например не будет использоваться пагинация, лучше снизить нагрузку на сервер и отдавать в ответе только необходимые поля.
2. Почему во мн. числе?
3. Где mixin?

2022-05-22 06:13 UTC, chrn-feip commented on backend_fefu_3_6/app/Http/Resources/ProductResources.php
> +            'categories' => new CategoriesResources(
Почему во мн. числе, если у товара одна категория может быть?

2022-05-22 06:13 UTC, chrn-feip commented on backend_fefu_3_6/app/Http/Resources/AttributeValueResource.php
> + * @mixin Categories
1. Код не тестируем, да? Тут другая модель
2. Ещё и число множественное зачем-то

2022-05-22 06:13 UTC, chrn-feip commented on backend_fefu_3_6/app/Http/Resources/AttributeValueResource.php
> +            'name' => $this->name,
В правильной модели нет такого поля

2022-05-22 06:13 UTC, chrn-feip commented on backend_fefu_3_6/app/Models/ProductCategory.php
> +    {
Сделайте тут ещё проверку, что коллекция $categories не пустая, иначе запрос whereIn упадёт для пустого массива параметров. Если коллекция пуста, то` throw new Exception(<Текст ошибки о том, что категории не переданы>)`. А в контроллерах, где вызывается `getTreeProductsBuilder`, делайте вызов внутри try-catch и в catch ветке делайте `abort(422, $exception->getMessage())`.

2022-05-22 06:13 UTC, chrn-feip commented on backend_fefu_3_6/app/Http/Controllers/Api/CategoriesApiController.php
> +use App\OpenApi\Responses\catalog\categories\AllCategoriesResponse;
Наименования директорий с большой буквы должны быть. Соответственно, в неймспейсах тоже с большой буквы.

2022-05-22 06:13 UTC, chrn-feip commented on backend_fefu_3_6/app/OpenApi/Responses/catalog/products/ShowProductResponse.php
> +class ShowProductResponse extends ResponseFactory
Тоже разные ресурсы/схемы товара должны быть отображены. Для show полный, для списка сокращённый.

2022-05-22 16:59 UTC, Vypsen commented
сделал

2022-05-23 02:43 UTC, chrn-feip requested changes

2022-05-23 02:43 UTC, chrn-feip commented on backend_fefu_3_6/app/Http/Controllers/Api/ProductApiController.php
> +        try {
Не здесь же. Где вы тут видите вызов метода getTreeProductBuilder?

2022-05-23 02:43 UTC, chrn-feip commented on backend_fefu_3_6/app/Http/Controllers/Api/ProductApiController.php
> +        return new FullInfoProductCategoryResource(
Почему ProductCategory, если товар?

2022-05-23 02:43 UTC, chrn-feip commented on backend_fefu_3_6/app/Http/Controllers/Web/ProductWebController.php
> +        try {
Аналогично

2022-05-23 02:43 UTC, chrn-feip commented on backend_fefu_3_6/app/Http/Resources/Catalog/AttributeValueResource.php
> + * @mixin ProductCategory
Вы понимаете смысл этой аннотации? Та модель, которая написана в mixin, подставляется вместо $this ниже в коде. Вы тут создали и назвали ресурс как будто для значения атрибута товара, а модель написали категории товара.

2022-05-23 02:43 UTC, chrn-feip commented on backend_fefu_3_6/app/Http/Resources/Catalog/FullInfoProductCategoryResource.php
> +class FullInfoProductCategoryResource extends JsonResource
1. Плохое название. Вы же делаете ресурс полного отображения товара, причём тут категория? DetailedProductResource тут, например, и ListProductResource для сокращенного варианта для списка. Или оставить ShortInfoProductResource для списка, а этот переименовать в FullInfoProductResource.
2. Для этого ресурса всё ещё не хватает mixin аннотации

2022-05-23 02:43 UTC, chrn-feip commented on backend_fefu_3_6/api-docs.json
> +            "Product": {
Что-то не вижу тут изменений. Должны быть две схема для товара - сокращённая и полная, аналогично тому, как вы ресурсы сделали. Перегенерируйте документацию.

2022-05-23 02:43 UTC, chrn-feip commented on backend_fefu_3_6/app/Models/ProductCategory.php
> +        if ($categories === null) {
Не null. У вас тут не может быть null по определению - тип аргумента Collection. Надо проверить, что коллекция не пуста - $categories->isEmpty()

2022-05-23 02:43 UTC, chrn-feip commented on backend_fefu_3_6/app/OpenApi/Responses/catalog/products/AllProductsCategory.php
> +                        Schema::array('data')->items(FullInfoProductSchema::ref()),
Здесь как раз сокращённая схема, это же список с пагинацией.

2022-05-23 02:43 UTC, chrn-feip commented on backend_fefu_3_6/app/OpenApi/Responses/catalog/products/AllProductsCategory.php
> +class AllProductsCategory extends ResponseFactory
Неудачное название. Вы выводите список товаров, а название это не отражает. CategoryProductsResponse или CategoryProductListResponse

2022-05-23 02:43 UTC, chrn-feip commented on backend_fefu_3_6/app/OpenApi/Responses/catalog/products/ShowProductResponse.php
> +                    ShortInfoProductSchema::ref('data')
Здесь полная схема товара

2022-05-23 04:24 UTC, chrn-feip requested changes

2022-05-23 04:24 UTC, chrn-feip commented on backend_fefu_3_6/app/Http/Controllers/Api/ProductApiController.php
> +use App\OpenApi\Responses\catalog\products\CategoryProductListResponse;
Опять со строчными буквами директории

2022-05-23 04:24 UTC, chrn-feip commented on backend_fefu_3_6/app/OpenApi/Schemas/FullInfoProductSchema.php
> +        return Schema::object('full_info')
FullInfoProduct

2022-05-23 04:24 UTC, chrn-feip commented on backend_fefu_3_6/app/OpenApi/Responses/catalog/products/ShowProductResponse.php
> +                    FullInfoProductSchema::ref('full_info')
Верните data

2022-05-23 04:24 UTC, chrn-feip commented on backend_fefu_3_6/app/OpenApi/Schemas/ShortInfoProductSchema.php
> +        return Schema::object('Product')
ShortInfoProduct

2022-05-23 04:24 UTC, chrn-feip commented
И документацию перегенерируйте после правок

2022-05-23 05:34 UTC, merged